### ISSUE TITLE
Can't build seajax on mac

### ISSUE THREAD

**Issue by eighteight** [seajax/seajax#6]
Eights-Book-2:Scripts eight$ npm install
module.js:338
    throw err;
          ^
Error: Cannot find module 'umask'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/umask.js:1:75)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
Eights-Book-2:Scripts eight$

**Comment by cpaulin** [comment]
Using the pivotviewer canvas template, I am getting odd behavior. I am attempting to draw a canvas element with a picture in it. The image loads fine in IE, flickers and can disappear in Firefox, and does not appear at all in Chrome/Safari. Here is a simple template that is not working. I don't want to use just the image template, because I want to draw images and text on the canvas. Can anyone tell me why my .drawimage does not work in the canvas template?

viewer.setTemplates([
                {
                type: "canvas",
                width: 438,
                height: 300,
                template: function (ctx, x, y, w, h, item) {
                    ctx.strokeStyle = "black";
                    ctx.lineWidth = w / 100;
                    ctx.strokeRect(x + w / 200, y + w / 200, .99 * w, h - .01 * w);
                    var img = new Image();
			img.onload = function () {
				ctx.drawImage(img, x, y, w, h);
				}
                    img.src = 'http://www.html5canvastutorials.com/demos/assets/darth-vader.jpg';
                    }
                }
            ]);

**Comment by sethobrien** [comment]
Hi cpaulin,

Thanks for your interest! In order to do animations and such, the Viewer regularly clears its entire view and tells each element to redraw itself. It seems that the particular timing of when the screen repaints is different on various browsers, but in general I'd expect that a solution like the following might be beneficial.

    var loadedImages = {}; // a set of images by source URL so we don't have to re-decode
    viewer.setTemplates([
        {
            type: "canvas",
            width: 438,
            height: 300,
            template: function (ctx, x, y, w, h, item) {
                ctx.strokeStyle = "black";
                ctx.lineWidth = w / 100;
                ctx.strokeRect(x + w / 200, y + w / 200, .99 * w, h - .01 * w);
                var src = 'http://www.html5canvastutorials.com/demos/assets/darth-vader.jpg'; // would probably vary by item
                var img = loadedImages[src];
                if (!img) {
                    var img = loadedImages[src] = new Image();
                    img.src = src;
                }
                if (img.complete) {
                    ctx.drawImage(img, x, y, w, h);
                    // returning true means this item doesn't need to redraw itself next frame (unless viewport moves and everybody must redraw)
                    return true;
                }
            }
        }
    ]);

Since the viewer is trying to redraw every frame anyway, we don't necessarily need to wait for a `load` event, we can just check the image's `complete` property at the time we are asked to draw the element. Once the image has loaded and drawn successfully, we can return true to notify the viewer that we don't require an update on the next frame; this can help CPU usage a lot by stopping the redraw cycle until the user does something. A more advanced solution would also include an `error` handler for the image, so that we can return true after either successful download or failure.

**Comment by sethobrien** [comment]
And @eighteight , I'm sorry we just derailed your issue thread. I don't have a Mac and so I can't be of much use to you, but perhaps some other members of the community here could help (summoning @gasi ).

**Comment by gasi** [comment]
@eighteight Which version of Node.js / npm do you have?

I just tried with a fresh `git clone` and it worked:

```bash
> node --version
v0.10.26

> npm --version
1.4.23

> npm install .
uglify-js@2.4.24 node_modules/uglify-js
├── uglify-to-browserify@1.0.2
├── async@0.2.10
├── source-map@0.1.34 (amdefine@1.0.0)
└── yargs@3.5.4 (decamelize@1.0.0, camelcase@1.2.1, window-size@0.1.0, wordwrap@0.0.2)

jshint@2.8.0 node_modules/jshint
├── strip-json-comments@1.0.4
├── exit@0.1.2
├── shelljs@0.3.0
├── console-browserify@1.1.0 (date-now@0.1.4)
├── minimatch@2.0.10 (brace-expansion@1.1.0)
├── lodash@3.7.0
├── cli@0.6.6 (glob@3.2.11)
└── htmlparser2@3.8.3 (domelementtype@1.3.0, entities@1.0.0, domhandler@2.3.0, readable-stream@1.1.13, domutils@1.5.1)
```
